services:
  postgres:
    image: postgres:latest
    container_name: library-postgres
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
